"""Do changes

Revision ID: 610bfffa36a3
Revises: bb1f3b6a61ff
Create Date: 2024-03-29 23:14:16.219280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '610bfffa36a3'
down_revision: Union[str, None] = 'bb1f3b6a61ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('post', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
