"""Fixes

Revision ID: bb1f3b6a61ff
Revises: f62d28d1df13
Create Date: 2024-03-29 15:20:23.003889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb1f3b6a61ff'
down_revision: Union[str, None] = 'f62d28d1df13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'picture_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('post', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'picture_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
